### ISSUE TITLE
Support spaCy v3.0

### ISSUE THREAD

**Issue by talmago** [talmago/spacy_ke#2]
_Originally posted by @kavorite in https://github.com/talmago/spacy_ke/issues/1#issuecomment-798971916_

**Comment by talmago** [comment]
https://github.com/talmago/spacy_ke/blob/master/examples/example_spacy_v3.py

**Comment by red1** [comment]
Hello, When I install this through pip install it is downgrading my spacy from 3, to 2.2.4. 
Are you planning to release a fix for this ?

**Comment by talmago** [comment]
@red1 spacy V3 support is WIP. Once ready, i do plan to release it. 

Until next release PYPI distribution will install spacy v2.2.X for you to eliminate breaking changes.
You can possibly work around this by using `pip install --no-deps spacy_ke`. If you go with this option, make sure to install the [requirements](https://github.com/talmago/spacy_ke/blob/master/setup.py#L68).

**Comment by talmago** [comment]
Fixed in this [PR](https://github.com/talmago/spacy_ke/pull/10).

Will be available in next release.
